parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  jquery: true
  es6: true
extends:
  - standard
  - standard-react
plugins:
  - react
  - import
globals:
  expect: false
rules:
  #common
  comma-dangle: off
  # React common rules
  react/jsx-boolean-value: [ error, never ]
  react/jsx-closing-bracket-location: [ warn, line-aligned ]
  react/jsx-indent-props: [ warn, 2 ]
  react/jsx-no-bind: off
  react/jsx-no-undef: error
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-wrap-multilines: error
  react/no-deprecated: warn
  react/no-unknown-property: error
  react/prop-types: warn
  react/react-in-jsx-scope: error
  react/self-closing-comp: error
  react/sort-comp: [ error, {
    order: [
      "constructor",
      "lifecycle",
      "everything-else",
      "/^on.+$/",
      "/^render.+$/",
      "render"
    ]
  } ]
